/* WorkflowKit Observatory — main app */

const { useState, useEffect, useMemo, useRef } = React;
const { sessions: SESSIONS, edges: EDGES, timelines: TIMELINES, logs: LOGS, toolUsage: TOOLS, now: NOW, helpers } = window.WK_DATA;
const { fmtTime, fmtTimeMs, pad } = helpers;

/* AnimatedNumber — tweens the displayed value whenever `value` changes and
   flashes a tint (green up / red down). Used anywhere a live count updates. */
function AnimatedNumber({ value, format = (n) => Math.round(n).toLocaleString(), className = "", duration = 700 }) {
  const [display, setDisplay] = React.useState(value);
  const [flash, setFlash] = React.useState(null); // null | 'up' | 'down'
  const fromRef = useRef(value);
  const prevRef = useRef(value);
  const rafRef = useRef(0);

  useEffect(() => {
    if (value === prevRef.current) return;
    const from = fromRef.current;
    const to = value;
    const dir = to >= prevRef.current ? "up" : "down";
    prevRef.current = value;
    const start = performance.now();
    setFlash(dir);
    cancelAnimationFrame(rafRef.current);
    const tick = (t) => {
      const p = Math.min(1, (t - start) / duration);
      const eased = 1 - Math.pow(1 - p, 3); // easeOutCubic
      const cur = from + (to - from) * eased;
      fromRef.current = cur;
      setDisplay(cur);
      if (p < 1) rafRef.current = requestAnimationFrame(tick);
      else { fromRef.current = to; setDisplay(to); setTimeout(() => setFlash(null), 350); }
    };
    rafRef.current = requestAnimationFrame(tick);
    return () => cancelAnimationFrame(rafRef.current);
  }, [value, duration]);

  return <span className={`anim-num ${flash ? "flash-" + flash : ""} ${className}`}>{format(display)}</span>;
}

const VIEWS = [
  { key: "timeline", label: "Timeline", code: "00" },
  { key: "graph", label: "Agent Graph", code: "01" },
  { key: "tokens", label: "Tokens", code: "02" },
  { key: "diag", label: "Diagnostics", code: "03" },
];

const DEFAULTS = /*EDITMODE-BEGIN*/{
  "palette": "orange",
  "scanlines": true,
  "scanStrength": 22,
  "density": "regular",
  "showWatermark": false
}/*EDITMODE-END*/;

function App() {
  const [view, setView] = useState("repos");
  const [selected, setSelected] = useState(SESSIONS[0].id);
  const [repoFilter, setRepoFilter] = useState(null);   // cwd string or null
  const [sessionChosen, setSessionChosen] = useState(false); // gates session-dependent views
  const [clock, setClock] = useState(NOW);
  // live token bump: extra tokens generated by the active live-tail session,
  // surfaced app-wide (header total) so updates animate everywhere, not just Timeline.
  const [liveBump, setLiveBump] = useState(0);
  useEffect(() => { setLiveBump(0); }, [selected]);
  const baseGlobalTokens = useMemo(() => SESSIONS.reduce((a, s) => a + s.tokens_used, 0), []);

  // tweaks
  const [tweaks, setTweak] = useTweaks(DEFAULTS);

  useEffect(() => {
    const root = document.documentElement;
    root.setAttribute("data-palette", tweaks.palette);
    root.style.setProperty("--scan-strength", String(tweaks.scanStrength / 100));
  }, [tweaks.palette, tweaks.scanStrength]);

  // tick the header clock
  useEffect(() => {
    const id = setInterval(() => setClock((c) => new Date(c.getTime() + 1000)), 1000);
    return () => clearInterval(id);
  }, []);

  const session = SESSIONS.find((s) => s.id === selected) || SESSIONS[0];

  // Drill-down gating: pick a repo → must pick a session → session-dependent views unlock.
  // Selecting a new repo wipes the chosen-session state so the user re-selects.
  const pickRepo = (cwd) => { setRepoFilter(cwd); setSessionChosen(false); setView("sessions"); };
  const pickSession = (id) => { setSelected(id); setSessionChosen(true); setView("timeline"); };
  // Repo shown in the header button: the explicitly-selected repo. Only the
  // Repos browser shows the plain "REPOS" label.
  const headerRepo = repoFilter;
  const showRepoName = view !== "repos" && !!headerRepo;

  return (
    <div className="shell" data-screen-label={`Observatory · ${view}`}>
      <TopHazardStrip clock={clock} />

      <header className="header">
        <button
          className="repos-btn"
          data-active={view === "repos"}
          data-has-repo={!!showRepoName}
          data-rail={view !== "repos" ? "on" : undefined}
          onClick={() => setView("repos")}
          title={headerRepo ? `Repo: ${headerRepo} — click to browse all repos` : "Browse all repos"}
        >
          <span className="mark" aria-hidden="true"></span>
          {showRepoName ? (
            <span className="repos-id">
              <span className="repos-kicker">▸ REPO</span>
              <span className="repos-name">{headerRepo.split("/").pop()}</span>
            </span>
          ) : (
            <span className="lbl">REPOS</span>
          )}
          <span className="caret" aria-hidden="true">▸</span>
        </button>

        <SessionSquare
          session={session}
          chosen={sessionChosen}
          disabled={!repoFilter}
          onClick={() => { if (repoFilter) setView("sessions"); }}
          active={view === "sessions"}
          railStart={view !== "repos" && (sessionChosen || view === "sessions")}
        />

        <nav className="nav">
          {VIEWS.map((v, i) => {
            const activeIdx = VIEWS.findIndex((x) => x.key === view);
            const inRail = sessionChosen && activeIdx >= 0 && i <= activeIdx;
            return (
              <button
                key={v.key}
                data-active={view === v.key}
                data-rail={inRail ? "on" : undefined}
                disabled={!sessionChosen}
                onClick={() => { if (sessionChosen) setView(v.key); }}
                title={!sessionChosen ? "Select a session first" : v.label}
              >
                <span className="idx">{v.code}</span>
                <span>{v.label}</span>
              </button>
            );
          })}
        </nav>

        <div className="right">
          <div className="stat">
            <div className="v num">{SESSIONS.length}</div>
            <div className="l">Sessions</div>
          </div>
          <div className="stat">
            <div className="v num warn-c">{SESSIONS.reduce((a, s) => a + (s.warnings > 0 ? 1 : 0), 0)}</div>
            <div className="l">w/ Warn</div>
          </div>
          <div className="stat">
            <div className="v num"><AnimatedNumber value={baseGlobalTokens + liveBump} format={(n) => Math.round(n / 1000) + "K"} /></div>
            <div className="l">Tokens</div>
          </div>
          <div className="stat">
            <div className="v num cyan-c">{fmtTime(clock)}</div>
            <div className="l">UTC-7 · LOCAL</div>
          </div>
        </div>
      </header>

      <main className="main">
        {view === "repos" && (
          <ReposView
            onPickRepo={pickRepo}
            onPickSession={pickSession}
            setView={setView}
          />
        )}
        {view === "sessions" && (
          <SessionsView
            selected={selected}
            sessionChosen={sessionChosen}
            onPickSession={pickSession}
            setView={setView}
            repoFilter={repoFilter}
            setRepoFilter={setRepoFilter}
            onTokenBump={setLiveBump}
          />
        )}
        {view === "timeline" && (
          <TimelineView session={session} setSelected={setSelected} setView={setView} onTokenBump={setLiveBump} />
        )}
        {view === "graph" && (
          <GraphView selected={selected} setSelected={setSelected} setView={setView} />
        )}
        {view === "tokens" && <TokensView session={session} setSelected={setSelected} setView={setView} />}
        {view === "diag" && <DiagnosticsView session={session} setSelected={setSelected} setView={setView} />}
      </main>

      <StatusBar view={view} clock={clock} session={session} />

      <TweaksPanel title="Observatory Tweaks">
        <TweakSection title="Palette">
          <TweakRadio
            label="Channel"
            value={tweaks.palette}
            onChange={(v) => setTweak("palette", v)}
            options={[
              { value: "orange", label: "Orange" },
              { value: "amber", label: "Amber" },
              { value: "red", label: "Red" },
              { value: "cyan", label: "Cyan" },
            ]}
          />
        </TweakSection>
        <TweakSection title="CRT Effect">
          <TweakToggle label="Scanlines" value={tweaks.scanlines} onChange={(v) => setTweak("scanlines", v)} />
          <TweakSlider label="Scan strength" value={tweaks.scanStrength} min={0} max={60} step={1} onChange={(v) => setTweak("scanStrength", v)} />
        </TweakSection>
        <TweakSection title="Chrome">
          <TweakToggle label="Watermark" value={tweaks.showWatermark} onChange={(v) => setTweak("showWatermark", v)} />
        </TweakSection>
      </TweaksPanel>

      {tweaks.scanlines && <div className="scanlines"></div>}
      <div className="crt-vignette"></div>
      {tweaks.showWatermark && <Watermark />}
    </div>
  );
}

/* --- Thread Navigator — lives in the Timeline sidebar.
   Renders the FULL agent tree rooted at the current session's root, so from
   any sub-agent you can still see (and jump to) the parent, siblings and any
   other node. The active thread is marked HERE. ---- */
function ThreadNav({ session, onSelect, liveTotal }) {
  const root = getRootSession(session);
  const rows = [];
  const walk = (node, depth) => {
    rows.push({ node, depth });
    SESSIONS.filter((s) => s.parent_id === node.id)
      .sort((a, b) => a.created_at - b.created_at)
      .forEach((c) => walk(c, depth + 1));
  };
  walk(root, 0);

  const edgeStatus = (id) => EDGES.find((e) => e.child === id)?.status;
  const idLabel = (s) => s.thread_source === "subagent"
    ? `SUB · ${(s.agent_role || "worker").toUpperCase()}`
    : "USER · ROOT";
  const nameLabel = (s) => s.thread_source === "subagent" ? s.agent_nickname : s.title;

  return (
    <div className="thread-nav">
      <div className="panel-tit">
        <span className="dot"></span><span>Agent Tree</span>
        <span className="spacer"></span>
        <span className="meta">{rows.length} thread{rows.length === 1 ? "" : "s"}</span>
      </div>
      <div className="thread-nav-body">
        {rows.map(({ node, depth }) => {
          const here = node.id === session.id;
          const isSub = node.thread_source === "subagent";
          const open = edgeStatus(node.id) === "open";
          const tone = toneForDepth(depth);
          return (
            <button
              key={node.id}
              className="thread-row"
              data-here={here}
              data-depth={depth}
              data-tone={tone}
              onClick={here ? undefined : () => onSelect(node.id)}
              style={{ "--depth": depth }}
              title={here ? "Current thread" : `Open ${nameLabel(node)}'s timeline`}
            >
              {depth > 0 && <span className="tn-connector" aria-hidden="true">└</span>}
              <span className="tn-tab" data-tone={tone}></span>
              <span className="tn-text">
                <span className="tn-kicker">{idLabel(node)}</span>
                <span className="tn-name">{nameLabel(node)}</span>
              </span>
              <span className="tn-meta">
                {here && <span className="tn-tok num"><AnimatedNumber value={liveTotal != null ? liveTotal : node.tokens_used} format={(n) => (n / 1000).toFixed(1) + "K"} /></span>}
                {here && <span className="tn-here">● HERE</span>}
                {!here && open && <span className="tn-dot" aria-label="open" />}
                {!here && <span className="num">{(node.tokens_used / 1000).toFixed(1)}K</span>}
              </span>
            </button>
          );
        })}
      </div>
    </div>
  );
}

/* --- Session square in header — identifies the selected session, its place
   in the agent hierarchy (parent / sub-agent / sub-sub-agent) and lineage ---- */
function SessionSquare({ session, onClick, active, railStart, chosen, disabled }) {
  // gated states: no repo yet (disabled) → repo chosen but no session (prompt) → session chosen (full)
  if (disabled || !chosen) {
    return (
      <button
        className="session-sq"
        data-empty="true"
        data-disabled={disabled ? "true" : undefined}
        data-active={active}
        data-rail={railStart ? "on" : undefined}
        onClick={onClick}
        disabled={disabled}
        title={disabled ? "Select a repo first" : "Select a session to inspect"}
      >
        <span className="ss-bars ss-bars-empty" aria-hidden="true">
          <span className="ss-bar" data-lvl="0" style={{ opacity: 0.3 }}></span>
        </span>
        <span className="ss-body">
          <span className="ss-top"><span className="ss-depth ss-depth-empty">SESSION</span></span>
          <span className="ss-name ss-name-empty">{disabled ? "— select a repo —" : "▸ select a session"}</span>
        </span>
      </button>
    );
  }
  const depth = sessionDepth(session);
  const tone = depth === 0 ? "primary" : depth === 1 ? "amber" : "cyan";
  const isSub = depth > 0;
  const name = isSub ? (session.agent_nickname || "—") : session.title;
  const lineage = sessionLineage(session);
  return (
    <button
      className="session-sq"
      data-tone={tone}
      data-active={active}
      data-rail={railStart ? "on" : undefined}
      onClick={onClick}
      title={`Selected session — ${depthLabel(depth)}${isSub ? " · " + session.agent_role : ""}\n${lineage.map((a) => a.parent_id ? a.agent_nickname : "ROOT").join(" → ")}\nClick to browse sessions`}
    >
      <span className="ss-bars" aria-hidden="true">
        {lineage.map((node, i) => (
          <span key={i} className="ss-bar" data-lvl={Math.min(i, 2)} data-current={i === lineage.length - 1}></span>
        ))}
      </span>
      <span className="ss-body">
        <span className="ss-top">
          <span className="ss-depth">{depthLabel(depth)}</span>
          {isSub && <span className="ss-role">· {session.agent_role}</span>}
        </span>
        <span className="ss-name">{name}</span>
      </span>
      <span className="ss-tok num">{(session.tokens_used / 1000).toFixed(1)}K</span>
      <span className="ss-arrow" aria-hidden="true">▸</span>
    </button>
  );
}

/* --- Top hazard strip with center wordmark ---- */
function TopHazardStrip({ clock }) {
  return (
    <div className="top-hazard" style={{ background: "var(--bg-1)" }}>
      <Hazard kind="primary" style={{ height: 22, flex: 1 }} />
      <div className="center" style={{ display: "flex", alignItems: "center", gap: 14 }}>
        <span style={{ fontSize: 11, color: "var(--ink-dim)", letterSpacing: "0.3em" }}>SYS:</span>
        <span>OBSERVATORY · 観測装置</span>
        <span className="jp" style={{ fontSize: 11, color: "var(--ink-dim)" }}>機密 / レベル 7</span>
        <span className="blink" style={{ color: "var(--warn)", fontSize: 11, letterSpacing: "0.3em" }}>● LIVE</span>
      </div>
      <Hazard kind="primary" style={{ height: 22, flex: 1 }} />
    </div>
  );
}

/* --- Status bar (footer) ---- */
function StatusBar({ view, clock, session }) {
  const tickerItems = [
    "PATTERN: CODEX OPS — NORMAL",
    "BACKFILL · OK · last_watermark=2026-05-26T17:59:44Z",
    "logs_2 ingest queue · 0 / capacity 1024",
    "rate_limit · primary 31% · secondary 18%",
    "session " + session.id.slice(0, 18) + " · ACTIVE",
    "MEMORY MODE · enabled",
  ];
  return (
    <div className="status">
      <span className="seq">▸ {view.toUpperCase()}</span>
      <span className="ticker-wrap">
        <span className="ticker">
          {tickerItems.concat(tickerItems).map((t, i) => (
            <span key={i} style={{ marginRight: 36 }}>// {t}</span>
          ))}
        </span>
      </span>
      <span>$CODEX_HOME = ~/.codex</span>
      <span><span className="live">●</span> LINK OK</span>
      <span className="num">{fmtTime(clock)}</span>
    </div>
  );
}

function Watermark() {
  return (
    <div style={{
      position: "fixed",
      left: "50%",
      bottom: 30,
      transform: "translateX(-50%)",
      display: "flex",
      alignItems: "center",
      gap: 14,
      padding: "4px 14px",
      background: "rgba(5, 4, 3, 0.9)",
      border: "1px solid var(--rule-soft)",
      fontFamily: "var(--display)",
      fontSize: 10,
      letterSpacing: "0.3em",
      color: "var(--ink-faint)",
      pointerEvents: "none",
      zIndex: 50,
      textTransform: "uppercase",
    }}>
      <span className="blink" style={{ color: "var(--warn)" }}>● REC</span>
      <span>FOR INTERNAL DIAGNOSTIC USE</span>
      <span>·</span>
      <span>UNAUTHORIZED ACCESS PROHIBITED</span>
      <span className="jp" style={{ letterSpacing: "0.18em", textTransform: "none" }}>関係者以外立入禁止</span>
    </div>
  );
}

/* ============================================================
   00 — REPOS OVERVIEW
   ============================================================ */

// Walk parent chain to find the root user session (the one with no parent_id)
function getRootSession(s) {
  let cur = s;
  while (cur && cur.parent_id) {
    const p = SESSIONS.find((x) => x.id === cur.parent_id);
    if (!p) break;
    cur = p;
  }
  return cur;
}

// 0 = parent/root, 1 = sub-agent, 2 = sub-sub-agent, …
function sessionDepth(s) {
  let d = 0, cur = s;
  while (cur && cur.parent_id) {
    const p = SESSIONS.find((x) => x.id === cur.parent_id);
    if (!p) break;
    d++; cur = p;
  }
  return d;
}

// root → … → current
function sessionLineage(s) {
  const chain = [];
  let cur = s;
  while (cur) {
    chain.unshift(cur);
    cur = cur.parent_id ? SESSIONS.find((x) => x.id === cur.parent_id) : null;
  }
  return chain;
}

const DEPTH_LABEL = ["PARENT", "SUB-AGENT", "SUB-SUB-AGENT"];
function depthLabel(d) { return DEPTH_LABEL[d] || `SUB ·L${d}`; }
// shared depth → color tone: 0 root (orange) · 1 sub (amber) · 2+ sub-sub (cyan)
function toneForDepth(d) { return d === 0 ? "primary" : d === 1 ? "amber" : "cyan"; }

function isDescendantOf(s, p) {
  let cur = s;
  while (cur && cur.parent_id) {
    if (cur.parent_id === p.id) return true;
    cur = SESSIONS.find((x) => x.id === cur.parent_id);
  }
  return false;
}

const TWELVE_H_MS = 12 * 60 * 60 * 1000;

function ReposView({ onPickRepo, onPickSession, setView }) {
  const repoCards = useMemo(() => {
    // Group by the cwd of the ROOT parent — subagents inherit their parent's repo
    const m = new Map();
    for (const s of SESSIONS) {
      if (s.parent_id) continue;
      const key = s.cwd;
      if (!m.has(key)) {
        m.set(key, {
          cwd: key,
          branch: s.git_branch,
          sha: s.git_sha,
          origin: s.git_origin_url,
          parents: [],
        });
      }
      m.get(key).parents.push(s);
    }

    return Array.from(m.values()).map((repo) => {
      const tree = repo.parents.map((p) => {
        const subs = SESSIONS.filter((s) => isDescendantOf(s, p));
        const lastTs = Math.max(p.updated_at.getTime(), ...subs.map((s) => s.updated_at.getTime()));
        return { parent: p, subs, lastTs };
      }).sort((a, b) => b.lastTs - a.lastTs);

      const allSessions = tree.flatMap(({ parent, subs }) => [parent, ...subs]);
      const active = tree.filter((t) => NOW.getTime() - t.lastTs <= TWELVE_H_MS);
      const totalTokens = allSessions.reduce((a, s) => a + s.tokens_used, 0);
      const totalWarn = allSessions.reduce((a, s) => a + s.warnings, 0);
      const openChildren = allSessions.reduce((a, s) => a + s.children_open, 0);
      const lastActivity = Math.max(...allSessions.map((s) => s.updated_at.getTime()));

      return {
        ...repo,
        tree,
        active,
        totalTokens,
        totalWarn,
        openChildren,
        sessionCount: allSessions.length,
        lastActivity,
      };
    }).sort((a, b) => b.active.length - a.active.length || b.lastActivity - a.lastActivity);
  }, []);

  const totalRepos = repoCards.length;
  const totalActive = repoCards.reduce((a, r) => a + r.active.length, 0);
  const totalSessions = repoCards.reduce((a, r) => a + r.sessionCount, 0);

  return (
    <div className="repos">
      <div className="repos-head">
        <HazardTag tone="primary">REPOS · INDEX</HazardTag>
        <div className="repos-head-stats">
          <div><span className="kicker">Repos</span><span className="num strong">{pad(totalRepos, 2)}</span></div>
          <div><span className="kicker">Active</span><span className="num strong">{totalActive}</span></div>
          <div><span className="kicker">Sessions</span><span className="num strong">{totalSessions}</span></div>
          <div><span className="kicker">Active = 12h</span><span className="num faint">window</span></div>
        </div>
      </div>

      <div className="repos-grid">
        {repoCards.map((r) => (
          <RepoCard
            key={r.cwd}
            r={r}
            onOpen={() => onPickRepo(r.cwd)}
            onJump={(id) => onPickSession(id)}
          />
        ))}
      </div>
    </div>
  );
}

function RepoCard({ r, onOpen, onJump }) {
  const repoName = r.cwd.split("/").pop();
  const parentDir = r.cwd.split("/").slice(0, -1).join("/") + "/";
  const ago = (t) => {
    const diff = Math.round((NOW - new Date(t)) / 60000);
    if (diff < 60) return `${diff}m`;
    if (diff < 1440) return `${Math.round(diff/60)}h`;
    return `${Math.round(diff/1440)}d`;
  };

  return (
    <article className="repo-card" data-has-active={r.active.length > 0}>
      <header className="repo-card-head" onClick={onOpen}>
        <div className="repo-tab" aria-hidden="true"></div>
        <div className="repo-id">
          <div className="repo-name">
            <span className="parent-dir">{parentDir}</span>
            <span className="leaf">{repoName}</span>
          </div>
          <div className="repo-branch">
            <span>{r.branch}</span>
            <span className="sep">·</span>
            <span className="num">{r.sha}</span>
            {r.origin && <><span className="sep">·</span><span className="muted">{r.origin.replace(/.*[:/]/, "")}</span></>}
          </div>
        </div>
        <div className="repo-stats">
          <div className={r.active.length > 0 ? "stat hot" : "stat"}>
            <span className="v num">{r.active.length}</span>
            <span className="l">Active 12h</span>
          </div>
          <div className="stat">
            <span className="v num">{(r.totalTokens / 1000).toFixed(0)}K</span>
            <span className="l">Σ Tokens</span>
          </div>
          <div className="stat">
            <span className={r.totalWarn > 0 ? "v num warn-c" : "v num"}>{r.totalWarn}</span>
            <span className="l">Warn</span>
          </div>
          <div className="stat">
            <span className={r.openChildren > 0 ? "v num warn-c blink" : "v num"}>{r.openChildren}</span>
            <span className="l">Open ◌</span>
          </div>
        </div>
      </header>

      <div className="repo-body">
        {r.active.length === 0 ? (
          <div className="repo-empty">
            <span className="faint">—— no activity in last 12h ——</span>
            <span className="muted" style={{ fontSize: 10, marginLeft: 8 }}>last seen {ago(r.lastActivity)} ago</span>
          </div>
        ) : (
          <>
            <div className="repo-section-lbl">▸ Active sessions <span className="muted">· last 12h</span></div>
            <div className="repo-tree">
              {r.active.map(({ parent, subs }) => (
                <div key={parent.id} className="repo-tree-row">
                  <div className="repo-row repo-row-parent" onClick={(e) => { e.stopPropagation(); onJump(parent.id); }}>
                    <span className="repo-row-bullet">▸</span>
                    <div className="repo-row-body">
                      <div className="repo-row-title">{parent.title}</div>
                      <div className="repo-row-meta">
                        <span className="chip" style={{ borderColor: "var(--primary)", color: "var(--primary)" }}>USER · ROOT</span>
                        <span className="num">{(parent.tokens_used / 1000).toFixed(1)}K</span>
                        <span className="muted">·</span>
                        <span className="muted num">{ago(parent.updated_at)} ago</span>
                        {parent.warnings > 0 && <span className="chip warn">▲ {parent.warnings}</span>}
                      </div>
                    </div>
                  </div>
                  {subs.length > 0 && (
                    <div className="repo-subs-row">
                      {subs.map((sub) => {
                        const isOpen = EDGES.find((e) => e.child === sub.id)?.status === "open";
                        return (
                          <button
                            key={sub.id}
                            type="button"
                            className="sub-chip"
                            data-status={isOpen ? "open" : "closed"}
                            onClick={(e) => { e.stopPropagation(); onJump(sub.id); }}
                            title={`${sub.agent_nickname} · ${sub.agent_role} · ${(sub.tokens_used/1000).toFixed(1)}K tok · ${ago(sub.updated_at)} ago`}
                          >
                            <span className="sub-chip-tab" aria-hidden="true"></span>
                            <span className="sub-chip-nick">{sub.agent_nickname}</span>
                            <span className="sub-chip-role">{sub.agent_role?.[0]?.toUpperCase() || "W"}</span>
                            <span className="sub-chip-tok num">{(sub.tokens_used/1000).toFixed(1)}K</span>
                            {isOpen && <span className="sub-chip-dot" aria-label="open" />}
                          </button>
                        );
                      })}
                    </div>
                  )}
                </div>
              ))}
            </div>
          </>
        )}
      </div>

      <footer className="repo-card-foot" onClick={onOpen}>
        <span>▸ OPEN {r.sessionCount} SESSION{r.sessionCount === 1 ? "" : "S"}</span>
        <span className="arrow">›</span>
      </footer>
    </article>
  );
}

/* ============================================================
   01 — SESSIONS OVERVIEW
   ============================================================ */
function SessionsView({ selected, onPickSession, sessionChosen, setView, repoFilter, setRepoFilter, onTokenBump }) {
  const [q, setQ] = useState("");
  const [filterSource, setFilterSource] = useState("all");
  const [filterRepo, setFilterRepo] = useState("all");
  const [filterFlag, setFilterFlag] = useState("all");
  const [filterBranch, setFilterBranch] = useState("all");

  // Live token deltas overlaid on active sessions — stands in for the SSE
  // index feed so token counts in the list tick up live.
  const [liveDeltas, setLiveDeltas] = useState({});
  useEffect(() => {
    // sessions considered "live": open children or activity within 12h
    const liveIds = SESSIONS
      .filter((s) => s.children_open > 0 || NOW.getTime() - s.updated_at.getTime() <= TWELVE_H_MS)
      .map((s) => s.id);
    if (liveIds.length === 0) return;
    const id = setInterval(() => {
      setLiveDeltas((prev) => {
        const next = { ...prev };
        // bump 1–3 random live sessions each tick
        const n = 1 + Math.floor(Math.random() * 3);
        for (let i = 0; i < n; i++) {
          const sid = liveIds[Math.floor(Math.random() * liveIds.length)];
          next[sid] = (next[sid] || 0) + 400 + Math.floor(Math.random() * 2600);
        }
        return next;
      });
    }, 2000);
    return () => clearInterval(id);
  }, []);
  const tokensOf = (s) => s.tokens_used + (liveDeltas[s.id] || 0);
  const isLiveSession = (s) => s.children_open > 0 || NOW.getTime() - s.updated_at.getTime() <= TWELVE_H_MS;
  const liveBumpTotal = Object.values(liveDeltas).reduce((a, b) => a + b, 0);
  // surface this view's cumulative live bump to the header counter (App.liveBump)
  useEffect(() => { if (onTokenBump) onTokenBump(liveBumpTotal); }, [liveBumpTotal]);

  const repos = useMemo(() => Array.from(new Set(SESSIONS.map((s) => s.cwd))), []);

  // Repo context — populated when `repoFilter` (inbound from Repos view) is set.
  // Swaps the left panel from global catalog → repo dossier.
  const repoCtx = useMemo(() => {
    if (!repoFilter) return null;
    const inRepo = SESSIONS.filter((s) => getRootSession(s).cwd === repoFilter);
    const parents = inRepo.filter((s) => !s.parent_id);
    const branches = Array.from(new Set(parents.map((p) => p.git_branch)));
    const sample = parents[0] || inRepo[0];
    return {
      cwd: repoFilter,
      branches,
      sample,
      sessions: inRepo,
      parents,
      active12h: inRepo.filter((s) => NOW.getTime() - s.updated_at.getTime() <= TWELVE_H_MS).length,
      tokens: inRepo.reduce((a, s) => a + s.tokens_used, 0),
      warnings: inRepo.reduce((a, s) => a + s.warnings, 0),
      openChildren: inRepo.reduce((a, s) => a + s.children_open, 0),
    };
  }, [repoFilter]);

  const matchPredicate = (s) => {
    if (q && !(`${s.title} ${s.first_user_message} ${s.id}`.toLowerCase().includes(q.toLowerCase()))) return false;
    if (filterSource !== "all" && s.thread_source !== filterSource) return false;
    if (filterRepo !== "all" && s.cwd !== filterRepo) return false;
    // Inbound repo filter (from Repos view): match the ROOT parent's cwd so subagents follow their owner.
    if (repoFilter && getRootSession(s).cwd !== repoFilter) return false;
    // Branch filter: scopes by the root parent's branch — only meaningful when inside a repo.
    if (filterBranch !== "all" && getRootSession(s).git_branch !== filterBranch) return false;
    if (filterFlag === "warnings" && s.warnings === 0) return false;
    if (filterFlag === "failed" && s.failed_tools === 0) return false;
    if (filterFlag === "open-child" && s.children_open === 0) return false;
    return !s.archived || filterFlag === "archived";
  };

  // Build a tree-grouped display order: parents at root, subagents nested under their parent.
  // Always include the parent of any visible sub so the tree connects upward.
  const { displayRows, matchedCount } = useMemo(() => {
    const matched = SESSIONS.filter(matchPredicate);
    const visibleIds = new Set(matched.map((s) => s.id));
    for (const s of matched) {
      let cur = s;
      while (cur && cur.parent_id) {
        visibleIds.add(cur.parent_id);
        cur = SESSIONS.find((x) => x.id === cur.parent_id);
      }
    }
    const visible = SESSIONS.filter((s) => visibleIds.has(s.id));
    const parents = visible.filter((s) => !s.parent_id).sort((a, b) => b.updated_at - a.updated_at);
    const rows = [];
    for (const p of parents) {
      rows.push({ s: p, depth: 0, matched: visibleIds.has(p.id) && matched.includes(p), isLastSub: false });
      // depth-first over descendants so each sub-sub sits under its own parent
      const walk = (node) => {
        const kids = visible
          .filter((s) => s.parent_id === node.id)
          .sort((a, b) => b.updated_at - a.updated_at);
        kids.forEach((k, i) => {
          rows.push({ s: k, depth: sessionDepth(k), matched: matched.includes(k), isLastSub: i === kids.length - 1 });
          walk(k);
        });
      };
      walk(p);
    }
    // Orphan subs (parent absent from SESSIONS) — render flat
    const orphans = visible.filter((s) => s.parent_id && !SESSIONS.find((x) => x.id === s.parent_id));
    for (const o of orphans) rows.push({ s: o, depth: 0, matched: matched.includes(o), isLastSub: false });
    return { displayRows: rows, matchedCount: matched.length };
  }, [q, filterSource, filterRepo, filterFlag, repoFilter, filterBranch]);

  const tokensByHour = useMemo(() => {
    // Token usage by hour over the last 12h. Scoped to the repo when one is active.
    const buckets = new Array(12).fill(0);
    const pool = repoFilter
      ? SESSIONS.filter((s) => getRootSession(s).cwd === repoFilter)
      : SESSIONS;
    pool.forEach((s) => {
      const hoursAgo = Math.min(11, Math.floor((NOW - s.updated_at) / (1000 * 60 * 60)));
      buckets[11 - hoursAgo] += s.tokens_used;
    });
    return buckets;
  }, [repoFilter]);

  return (
    <div className="overview">
      {/* SIDE: contextual — dossier when scoped to a repo, global catalog otherwise */}
      <aside className="ov-side">
        {repoCtx ? (
          <>
            {/* ── header: repo identity + back-to-repos ─────────────────────── */}
            <div className="ov-repo-head">
              <button className="ov-back" onClick={() => setView("repos")} title="Back to Repos">
                <span className="arrow">‹</span><span>ALL REPOS</span>
              </button>
              <div className="ov-repo-name">
                <span className="parent-dir">{repoCtx.cwd.split("/").slice(0, -1).join("/")}/</span>
                <span className="leaf">{repoCtx.cwd.split("/").pop()}</span>
              </div>
              <div className="ov-repo-meta">
                <span>{repoCtx.sample?.git_branch || "—"}</span>
                <span className="sep">·</span>
                <span className="num">{repoCtx.sample?.git_sha || "—"}</span>
                {repoCtx.sample?.git_origin_url && (
                  <>
                    <span className="sep">·</span>
                    <span className="muted">{repoCtx.sample.git_origin_url.replace(/.*[:/]/, "")}</span>
                  </>
                )}
              </div>
            </div>

            {/* ── scoped stats ──────────────────────────────────────────────── */}
            <div className="side-stat">
              <Stat label="Active 12h" value={repoCtx.active12h} sub="recent" />
              <Stat label="Sessions" value={repoCtx.sessions.length} sub="in repo" />
              <Stat label="Open ◌" value={repoCtx.openChildren} tone="warn" sub="awaiting" />
              <Stat label="Σ Tokens" value={<AnimatedNumber value={repoCtx.tokens + repoCtx.sessions.reduce((a, s) => a + (liveDeltas[s.id] || 0), 0)} format={(n) => (n / 1000).toFixed(0) + "K"} />} sub="repo total" />
            </div>

            <div className="filter-grp">
              <div className="lbl">Token usage · last 12h <span className="muted">· this repo</span></div>
              <VBars data={tokensByHour} h={42} />
              <div className="flex between mt-1" style={{ fontSize: 10, color: "var(--ink-dim)", letterSpacing: "0.18em" }}>
                <span>-12H</span><span>NOW</span>
              </div>
            </div>

            <div className="filter-grp" style={{ flex: 1, overflowY: "auto" }}>
              {repoCtx.branches.length > 1 && (
                <>
                  <div className="lbl">Branch</div>
                  <div className="row mb-2">
                    <button className="opt" data-on={filterBranch === "all"} onClick={() => setFilterBranch("all")}>All</button>
                    {repoCtx.branches.map((b) => (
                      <button key={b} className="opt" data-on={filterBranch === b} onClick={() => setFilterBranch(b)}>{b}</button>
                    ))}
                  </div>
                </>
              )}
              <div className="lbl">Thread source</div>
              <div className="row mb-2">
                {[["all", "All"], ["user", "User"], ["subagent", "Sub-agent"]].map(([v, l]) => (
                  <button key={v} className="opt" data-on={filterSource === v} onClick={() => setFilterSource(v)}>{l}</button>
                ))}
              </div>
              <div className="lbl">Flag</div>
              <div className="row">
                {[["all", "Any"], ["warnings", "Has warn"], ["failed", "Failed tool"], ["open-child", "Open child"], ["archived", "Archived"]].map(([v, l]) => (
                  <button key={v} className="opt" data-on={filterFlag === v} onClick={() => setFilterFlag(v)}>{l}</button>
                ))}
              </div>
            </div>

            <div style={{ padding: "10px 14px", borderTop: "1px solid var(--rule)", display: "flex", justifyContent: "space-between", fontSize: 10, color: "var(--ink-dim)", letterSpacing: "0.18em" }}>
              <span>RESULTS · {matchedCount}<span className="faint"> / {repoCtx.sessions.length}</span></span>
              <span className="warn-c blink">▸ LIVE</span>
            </div>
          </>
        ) : (
          <>
            <div style={{ padding: "14px 14px 10px", borderBottom: "1px solid var(--rule)" }}>
              <div className="kicker" style={{ color: "var(--primary)" }}>▸ Catalog</div>
              <div className="display" style={{ fontSize: 24, color: "var(--ink-strong)", marginTop: 4 }}>SESSION INDEX</div>
              <div className="muted" style={{ fontSize: 11, marginTop: 4 }}>state_5.sqlite · threads · {SESSIONS.length} of 673 visible</div>
            </div>

            <div className="side-stat">
              <Stat label="Active" value={SESSIONS.filter((s) => !s.archived).length} sub="not archived" />
              <Stat label="Sub-agents" value={SESSIONS.filter((s) => s.thread_source === "subagent").length} sub="subagent threads" />
              <Stat label="Open child" value={SESSIONS.reduce((a, s) => a + s.children_open, 0)} tone="warn" sub="awaiting" />
              <Stat label="Σ Tokens" value={<AnimatedNumber value={SESSIONS.reduce((a, s) => a + s.tokens_used, 0) + liveBumpTotal} format={(n) => (n / 1000).toFixed(0) + "K"} />} sub="all sessions" />
            </div>

            <div className="filter-grp">
              <div className="lbl">Token usage · last 12h</div>
              <VBars data={tokensByHour} h={42} />
              <div className="flex between mt-1" style={{ fontSize: 10, color: "var(--ink-dim)", letterSpacing: "0.18em" }}>
                <span>-12H</span><span>NOW</span>
              </div>
            </div>

            <div className="filter-grp" style={{ flex: 1, overflowY: "auto" }}>
              <div className="lbl">Thread source</div>
              <div className="row mb-2">
                {[["all", "All"], ["user", "User"], ["subagent", "Sub-agent"]].map(([v, l]) => (
                  <button key={v} className="opt" data-on={filterSource === v} onClick={() => setFilterSource(v)}>{l}</button>
                ))}
              </div>
              <div className="lbl">Repo · cwd</div>
              <div className="row mb-2">
                <button className="opt" data-on={filterRepo === "all"} onClick={() => setFilterRepo("all")}>All</button>
                {repos.map((r) => (
                  <button key={r} className="opt" data-on={filterRepo === r} onClick={() => setFilterRepo(r)}>{r.split("/").pop()}</button>
                ))}
              </div>
              <div className="lbl">Flag</div>
              <div className="row">
                {[["all", "Any"], ["warnings", "Has warn"], ["failed", "Failed tool"], ["open-child", "Open child"], ["archived", "Archived"]].map(([v, l]) => (
                  <button key={v} className="opt" data-on={filterFlag === v} onClick={() => setFilterFlag(v)}>{l}</button>
                ))}
              </div>
            </div>

            <div style={{ padding: "10px 14px", borderTop: "1px solid var(--rule)", display: "flex", justifyContent: "space-between", fontSize: 10, color: "var(--ink-dim)", letterSpacing: "0.18em" }}>
              <span>RESULTS · {matchedCount}</span>
              <span className="warn-c blink">▸ LIVE INDEX</span>
            </div>
          </>
        )}
      </aside>

      {/* MAIN TABLE */}
      <div className="ov-main">
        <div className="ov-toolbar">
          <div className="ov-search">
            <span className="sigil">QUERY:</span>
            <input
              placeholder='title · first user message · uuid'
              value={q}
              onChange={(e) => setQ(e.target.value)}
            />
            <span className="muted" style={{ fontSize: 10, letterSpacing: "0.2em" }}>↵ exec</span>
          </div>
          <div className="chip dim">SORT · updated_at ↓</div>
          <div className="chip dim">JOIN · thread_spawn_edges</div>
          <div className="chip">PROFILE · adam@local</div>
        </div>

        <div className="ov-table">
          <table className="tbl">
            <thead>
              <tr>
                <th style={{ width: 18 }}></th>
                <th style={{ width: 88 }}>Updated</th>
                <th>Title / Brief</th>
                <th style={{ width: 168 }}>Repo · branch</th>
                <th style={{ width: 130 }}>Model</th>
                <th style={{ width: 110 }}>Tokens</th>
                <th style={{ width: 84 }}>Source</th>
                <th style={{ width: 90 }}>Child</th>
                <th style={{ width: 84 }}>Warn</th>
                <th style={{ width: 18 }}></th>
              </tr>
            </thead>
            <tbody>
              {displayRows.map(({ s, depth, matched, isLastSub }, idx) => {
                const ago = Math.round((NOW - s.updated_at) / 60000);
                const active = sessionChosen && s.id === selected;
                return (
                  <tr
                    key={s.id}
                    data-active={active}
                    data-depth={depth}
                    data-dim={!matched}
                    data-last-sub={depth === 1 ? isLastSub : undefined}
                    onClick={() => onPickSession(s.id)}
                  >
                    <td className="muted num">{pad(idx + 1, 3)}</td>
                    <td className="num">
                      <div>{ago < 60 ? `${ago}m ago` : `${Math.round(ago/60)}h ago`}</div>
                      <div className="muted" style={{ fontSize: 10 }}>{fmtTime(s.updated_at)}</div>
                    </td>
                    <td>
                      <div className="strong tree-title" style={{ fontWeight: 600, marginBottom: 2 }}>
                        {depth > 0 && <span className="tree-connector" aria-hidden="true">{isLastSub ? "└" : "├"}</span>}
                        <span>{s.title}</span>
                      </div>
                      <div className="muted" style={{ fontSize: 11 }}>
                        <span className="arr">{s.first_user_message.slice(0, 92)}{s.first_user_message.length > 92 ? "…" : ""}</span>
                      </div>
                    </td>
                    <td>
                      <div>{s.cwd}</div>
                      <div className="muted" style={{ fontSize: 11 }}>
                        <span className="num">{s.git_sha || "—"}</span> · {s.git_branch}
                      </div>
                    </td>
                    <td>
                      <div>{s.model}</div>
                      <div className="muted" style={{ fontSize: 11 }}>effort · {s.reasoning_effort}</div>
                    </td>
                    <td>
                      <div className="num tok-cell">
                        <AnimatedNumber value={tokensOf(s)} format={(n) => Math.round(n).toLocaleString()} />
                        {isLiveSession(s) && <span className="tok-live" title="live">●</span>}
                      </div>
                      <SegBar count={12} value={Math.min(100, (tokensOf(s) / 200000) * 100)} hi={tokensOf(s) > 100000} />
                    </td>
                    <td>
                      {s.thread_source === "user" ? (
                        <span className="chip">USER</span>
                      ) : (
                        <span className="chip amber">SUB · {s.agent_role?.[0]?.toUpperCase() || "W"}</span>
                      )}
                      {s.agent_nickname && <div className="muted" style={{ fontSize: 10, marginTop: 4 }}>{s.agent_nickname}</div>}
                    </td>
                    <td>
                      {s.children > 0 ? (
                        <div>
                          <span className="num strong">{s.children}</span>
                          {s.children_open > 0 && <span className="warn-c"> · {s.children_open} open</span>}
                        </div>
                      ) : <span className="faint">—</span>}
                    </td>
                    <td>
                      {s.warnings > 0 ? (
                        <span className="chip warn">▲ {s.warnings}</span>
                      ) : <span className="faint">·</span>}
                      {s.failed_tools > 0 && <div className="warn-c" style={{ fontSize: 10, marginTop: 4 }}>✕ {s.failed_tools} fail</div>}
                    </td>
                    <td className="muted">›</td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}

/* ============================================================
   02 — TIMELINE
   ============================================================ */
function TimelineView({ session, setSelected, setView, onTokenBump }) {
  const baseEvents = TIMELINES[session.id] || TIMELINES[SESSIONS[0].id];
  const [filter, setFilter] = useState("all");
  const [scope, setScope] = useState("this"); // "this" | "all" (incl. sub-agents, recursively)
  const [windowMs, setWindowMs] = useState(0); // 0 === "all"
  const [expanded, setExpanded] = useState(new Set());

  // descendant sessions (sub-agents, sub-sub-agents, …) that actually have timelines
  const descendants = useMemo(
    () => SESSIONS.filter((s) => isDescendantOf(s, session) && TIMELINES[s.id]),
    [session.id]
  );
  // reset scope to "this" when switching to a session with no descendants
  useEffect(() => { if (descendants.length === 0) setScope("this"); }, [session.id]);

  // --- live tail: stands in for the SSE stream so the enter/update
  //     animations are demonstrable on this static mock ---
  const [live, setLive] = useState(false);
  const [liveEvents, setLiveEvents] = useState([]);
  const [liveTotal, setLiveTotal] = useState(session.tokens_used);
  const liveTotalRef = useRef(session.tokens_used);
  const streamRef = useRef(null);

  // reset live state whenever the viewed session changes
  useEffect(() => {
    setLiveEvents([]);
    setLive(false);
    setLiveTotal(session.tokens_used);
    liveTotalRef.current = session.tokens_used;
  }, [session.id]);

  // synthetic event generator
  useEffect(() => {
    if (!live) return;
    let n = 0;
    const id = setInterval(() => {
      n += 1;
      const ts = new Date();
      const stamp = ts.getTime();
      const r = Math.random();
      let ev;
      if (n % 4 === 0) {
        const bump = 900 + Math.floor(Math.random() * 4200);
        liveTotalRef.current += bump;
        setLiveTotal(liveTotalRef.current);
        if (onTokenBump) onTokenBump((b) => b + bump);
        const total = liveTotalRef.current;
        ev = { _id: "lv-" + stamp, _new: true, ts, kind: "token_count",
          total, input: Math.round(total * 0.82), output: Math.round(total * 0.18),
          cached: Math.round(total * 0.82 * 0.55),
          ctx_pct: Math.min(99, total / 2000), rate_pct: 42 + Math.floor(Math.random() * 34) };
      } else if (r < 0.42) {
        const tools = ["read_file", "grep", "edit_file", "run_terminal", "list_dir"];
        const name = tools[Math.floor(Math.random() * tools.length)];
        ev = { _id: "lv-" + stamp, _new: true, ts, kind: "tool_call", name,
          call_id: "c" + stamp, args: { path: "src/" + name + ".ts" } };
      } else if (r < 0.66) {
        ev = { _id: "lv-" + stamp, _new: true, ts, kind: "assistant", phase: "working",
          text: "Continuing analysis of the current task context…" };
      } else if (r < 0.84) {
        ev = { _id: "lv-" + stamp, _new: true, ts, kind: "tool_call", name: "spawn_agent",
          call_id: "c" + stamp, args: { nickname: "SCOUT-" + (n % 9), role: "worker", task: "investigate subsystem" } };
      } else {
        ev = { _id: "lv-" + stamp, _new: true, ts, kind: "warning",
          text: "Approaching context window soft limit." };
      }
      setLiveEvents((prev) => [...prev, ev]);
    }, 1700);
    return () => clearInterval(id);
  }, [live, session.id]);

  // Tag events with their source session so the list can show which agent each
  // came from (depth bars + name). In "all" scope, merge the current session's
  // events with every descendant's, sorted chronologically.
  const allEvents = useMemo(() => {
    const tag = (evs, src) => {
      const d = sessionDepth(src);
      const nm = src.thread_source === "subagent" ? (src.agent_nickname || "SUB") : "ROOT";
      return evs.map((e) => ({ ...e, _srcId: src.id, _srcName: nm, _srcDepth: d }));
    };
    const own = tag([...baseEvents, ...liveEvents], session);
    if (scope === "this") return own;
    let arr = own.slice();
    for (const d of descendants) arr = arr.concat(tag(TIMELINES[d.id] || [], d));
    // always strictly by event time, regardless of agent depth
    arr.sort((a, b) => a.ts - b.ts);
    return arr;
  }, [baseEvents, liveEvents, scope, descendants, session.id]);

  // newest is on top now — keep the stream pinned to the top while tailing
  useEffect(() => {
    if (live && streamRef.current) {
      streamRef.current.scrollTop = 0;
    }
  }, [liveEvents, live]);

  // Reference time = last event in the full session. Windowing trims earlier events;
  // the scrubber rail, tab counts and stream all reflect the same windowed slice.
  const refNow = allEvents[allEvents.length - 1].ts;
  const events = useMemo(
    () => (windowMs ? allEvents.filter((e) => refNow - e.ts <= windowMs) : allEvents),
    [allEvents, windowMs, refNow]
  );

  // Guard against an empty window (shouldn't happen since refNow is in-range, but safe)
  const t0 = (events[0] || allEvents[0]).ts;
  const tEnd = (events[events.length - 1] || allEvents[allEvents.length - 1]).ts;
  const span = Math.max(1, tEnd - t0);

  // per-source token deltas (chronological, so each agent's "Δ since last" is correct)
  const _prevBySrc = {};
  events.forEach((e) => {
    if (e.kind === "token_count") { e._delta = e.total - (_prevBySrc[e._srcId] || 0); _prevBySrc[e._srcId] = e.total; }
  });

  const filtered = events.filter((e) => {
    if (filter === "all") return true;
    if (filter === "msg") return e.kind === "user" || e.kind === "assistant" || e.kind === "agent_report";
    if (filter === "tool") return e.kind === "tool_call" || e.kind === "tool_output";
    if (filter === "skill") return e.kind === "skill_invoke";
    if (filter === "agent") return e.kind === "tool_call" && (e.name === "spawn_agent" || e.name === "wait_agent");
    if (filter === "warn") return e.kind === "warning" || (e.kind === "tool_output" && e.fail);
    if (filter === "token") return e.kind === "token_count";
    return true;
  });

  // join tool_call ↔ tool_output by call_id
  const outByCall = {};
  events.forEach((e) => { if (e.kind === "tool_output") outByCall[e.call_id] = e; });

  const toggle = (key) => {
    setExpanded((prev) => {
      const n = new Set(prev);
      if (n.has(key)) n.delete(key); else n.add(key);
      return n;
    });
  };

  // build scrubber dots
  const scrubDots = events.map((e, i) => ({
    pct: ((e.ts - t0) / span) * 100,
    kind: e.kind,
    i,
  }));

  return (
    <div className="timeline">
      {/* CENTER */}
      <section className="tl-main">
        <div className="tl-tabs">
          {[
            ["all", "All Events", events.length],
            ["msg", "Messages", events.filter((e) => e.kind === "user" || e.kind === "assistant" || e.kind === "agent_report").length],
            ["tool", "Tools", events.filter((e) => e.kind === "tool_call").length],
            ["skill", "Skills", events.filter((e) => e.kind === "skill_invoke").length],
            ["agent", "Agent Ops", events.filter((e) => e.kind === "tool_call" && (e.name === "spawn_agent" || e.name === "wait_agent")).length],
            ["token", "Tokens", events.filter((e) => e.kind === "token_count").length],
            ["warn", "Warnings", events.filter((e) => e.kind === "warning" || (e.kind === "tool_output" && e.fail)).length],
          ].map(([k, l, n]) => (
            <button key={k} data-on={filter === k} onClick={() => setFilter(k)}>
              {l} <span className="muted">·{n}</span>
            </button>
          ))}
          <div className="tl-range" role="group" aria-label="Time window">
            {descendants.length > 0 && (
              <>
                <span className="tl-range-lbl">▸ SCOPE</span>
                <button
                  data-on={scope === "this"}
                  onClick={() => setScope("this")}
                  title="Only events from this agent session"
                >THIS</button>
                <button
                  data-on={scope === "all"}
                  onClick={() => setScope("all")}
                  title="Include events from sub-agents and their sub-agents"
                >+SUBS</button>
                <span className="tl-range-div" aria-hidden="true"></span>
              </>
            )}
            <button
              className="tl-live-btn"
              data-on={live}
              onClick={() => setLive((v) => !v)}
              title={live ? "Pause live tail" : "Simulate live SSE stream"}
            >
              <span className="dot"></span>{live ? "LIVE" : "TAIL"}
            </button>
            <span className="tl-range-lbl">▸ WINDOW</span>
            {[
              [60 * 60 * 1000, "1H"],
              [4 * 60 * 60 * 1000, "4H"],
              [12 * 60 * 60 * 1000, "12H"],
              [0, "ALL"],
            ].map(([ms, l]) => (
              <button
                key={l}
                data-on={windowMs === ms}
                onClick={() => setWindowMs(ms)}
                title={ms ? `Show events from last ${l}` : "Show entire session"}
              >
                {l}
              </button>
            ))}
          </div>
        </div>

        <div className="tl-scrubber">
          <div className="hdr">
            <span><Reticle /> TURN 01 · {windowMs ? `LAST ${windowMs/3600000|0}H` : "TASK_STARTED → TASK_COMPLETE"} · DUR {Math.round((tEnd - t0)/1000)}s</span>
            <span>TTFT {session.ttft_ms}ms</span>
          </div>
          <div className="track">
            {scrubDots.map((d) => (
              <span key={d.i} style={{
                position: "absolute",
                left: `${d.pct}%`,
                top: "50%",
                width: d.kind === "token_count" ? 2 : 4,
                height: d.kind === "token_count" ? 28 : (d.kind === "warning" ? 22 : 14),
                transform: "translate(-50%, -50%)",
                background:
                  d.kind === "warning" ? "var(--warn)"
                  : d.kind === "tool_call" ? "var(--amber)"
                  : d.kind === "skill_invoke" ? "var(--skill)"
                  : d.kind === "user" ? "var(--cyan)"
                  : d.kind === "agent_report" ? "var(--good)"
                  : d.kind === "task_complete" ? "var(--ink-strong)"
                  : "var(--primary)",
                boxShadow: "0 0 6px currentColor",
                color: "var(--primary)",
              }}></span>
            ))}
            {/* axis ticks */}
            {[0, 25, 50, 75, 100].map((p) => (
              <span key={p} style={{
                position: "absolute", left: `${p}%`, bottom: 0, width: 1, height: 6, background: "var(--rule-strong)",
              }}></span>
            ))}
          </div>
        </div>

        <div className="tl-stream" ref={streamRef}>
          {(() => {
            // display newest-first; in "+SUBS" scope each row carries a left gutter
            // with depth bars + agent name so you can read each event's origin
            const display = filtered.slice().reverse();
            const out = [];
            display.forEach((e, i) => {
              const key = e._id || `${e._srcId || ""}-${e.ts.getTime()}-${i}`;
              const isOpen = expanded.has(key);
              const showSrc = scope === "all";
              out.push(
                <div key={key} className={"ev-wrap" + (e._new ? " ev-enter" : "") + (showSrc ? " with-src" : "")}>
                  {showSrc && (
                    <div className="ev-src-rail" data-tone={toneForDepth(e._srcDepth)} title={`${e._srcName} · ${depthLabel(e._srcDepth)}`}>
                      <span className="ev-src-bars" aria-hidden="true">
                        {Array.from({ length: e._srcDepth + 1 }).map((_, j) => <span key={j} className="ev-src-bar" data-lvl={Math.min(j, 2)}></span>)}
                      </span>
                      <span className="ev-src-name">{e._srcName}</span>
                    </div>
                  )}
                  <EventRow e={e} delta={e._delta} outByCall={outByCall} isOpen={isOpen} toggle={() => toggle(key)} onJump={(id) => { setSelected(id); }} />
                </div>
              );
            });
            return out;
          })()}
        </div>
      </section>

      {/* RIGHT — summary panels */}
      <aside className="tl-side-r">
        <ThreadNav session={session} onSelect={setSelected} liveTotal={liveTotal} />
        <div className="tl-vitals">
        <div className="panel-tit"><span className="dot"></span><span>Turn 01 · Vitals</span><span className="spacer"></span><span className="meta">live</span></div>
        <div style={{ padding: 14, overflow: "auto" }}>
          <div className="display" style={{ fontSize: 28, color: "var(--ink-strong)" }}>
            <AnimatedNumber value={liveTotal} format={(n) => (n / 1000).toFixed(1) + "K"} />
          </div>
          <div className="kicker" style={{ marginTop: -2 }}>Σ tokens · used {live && <span className="warn-c blink">· live</span>}</div>

          <div style={{ marginTop: 16 }}>
            <div className="flex between mb-1" style={{ fontSize: 10, letterSpacing: "0.18em", color: "var(--ink-dim)", textTransform: "uppercase" }}>
              <span>Context window</span><span className="num strong"><AnimatedNumber value={Math.min(99, Math.round((liveTotal / 200000) * 100))} format={(n) => Math.round(n) + "%"} /></span>
            </div>
            <SegBar count={24} value={Math.min(100, (liveTotal / 200000) * 100)} hi={liveTotal > 100000} />
          </div>

          <div style={{ marginTop: 16 }}>
            <div className="flex between mb-1" style={{ fontSize: 10, letterSpacing: "0.18em", color: "var(--ink-dim)", textTransform: "uppercase" }}>
              <span>Primary rate-limit</span><span className="num strong">54%</span>
            </div>
            <SegBar count={24} value={54} />
          </div>

          <div style={{ marginTop: 16 }}>
            <div className="flex between mb-1" style={{ fontSize: 10, letterSpacing: "0.18em", color: "var(--ink-dim)", textTransform: "uppercase" }}>
              <span>Secondary</span><span className="num strong">18%</span>
            </div>
            <SegBar count={24} value={18} />
          </div>

          <div style={{ marginTop: 20, borderTop: "1px solid var(--rule)", paddingTop: 12 }}>
            <div className="kicker mb-2">▸ Tool Usage · this turn</div>
            {Object.entries(events.filter((e) => e.kind === "tool_call").reduce((acc, e) => { acc[e.name] = (acc[e.name]||0)+1; return acc; }, {})).map(([n, c]) => (
              <div key={n} className="flex between" style={{ fontSize: 11, padding: "3px 0" }}>
                <span>{n}</span>
                <span className="num strong">{c}</span>
              </div>
            ))}
          </div>

          <button
            onClick={() => setView("graph")}
            style={{ marginTop: 16, width: "100%", padding: "10px 12px", border: "1px solid var(--primary)", color: "var(--primary)", fontFamily: "var(--display)", letterSpacing: "0.18em", textTransform: "uppercase", fontSize: 11, fontWeight: 700 }}
          >
            ▸ Open Agent Graph
          </button>
        </div>
        </div>
      </aside>
    </div>
  );
}

function EventRow({ e, delta, outByCall, isOpen, toggle, onJump }) {
  if (e.kind === "task_started") {
    return (
      <div className="ev" style={{ borderLeft: "1px solid var(--rule-strong)" }}>
        <div className="ts num">{fmtTimeMs(e.ts).slice(0, 12)}</div>
        <div className="body" style={{ borderColor: "var(--primary)" }}>
          <div className="head">
            <span className="who" style={{ color: "var(--primary)" }}>TURN 01 · TASK_STARTED</span>
            <span className="right">model {e.model} · effort {e.effort} · sandbox {e.sandbox}</span>
          </div>
        </div>
      </div>
    );
  }
  if (e.kind === "task_complete") {
    return (
      <div className="ev">
        <div className="ts num">{fmtTimeMs(e.ts).slice(0, 12)}</div>
        <div className="body" style={{ borderColor: "var(--good)" }}>
          <div className="head">
            <span className="who" style={{ color: "var(--good)" }}>▸ TASK_COMPLETE</span>
            <span className="right">dur {Math.round(e.duration_ms/1000)}s · ttft {e.ttft_ms}ms</span>
          </div>
          <pre>{e.last_agent_message}</pre>
        </div>
      </div>
    );
  }
  if (e.kind === "user") {
    return (
      <div className="ev user">
        <div className="ts num">{fmtTimeMs(e.ts).slice(0, 12)}</div>
        <div className="body">
          <div className="head"><span className="who user">USER</span><span>message</span></div>
          <pre>{e.text}</pre>
        </div>
      </div>
    );
  }
  if (e.kind === "assistant") {
    return (
      <div className="ev assistant">
        <div className="ts num">{fmtTimeMs(e.ts).slice(0, 12)}</div>
        <div className="body">
          <div className="head"><span className="who">ASSISTANT</span><span>{e.phase}</span></div>
          <pre>{e.text}</pre>
        </div>
      </div>
    );
  }
  if (e.kind === "agent_report") {
    return (
      <div className="ev spawn">
        <div className="ts num">{fmtTimeMs(e.ts).slice(0, 12)}</div>
        <div className="body" style={{ borderColor: "var(--good)" }}>
          <div className="head"><span className="who spawn">{e.from} · AGENT REPORT</span></div>
          <pre>{e.text}</pre>
        </div>
      </div>
    );
  }
  if (e.kind === "skill_invoke") {
    return (
      <div className="ev skill">
        <div className="ts num">{fmtTimeMs(e.ts).slice(0, 12)}</div>
        <div className="body" style={{ borderColor: "var(--skill)" }}>
          <div className="head">
            <span className="who skill">✦ SKILL · {e.name}</span>
            {e.call_id && <span>call_id {e.call_id}</span>}
            {e.status && <span className={e.status === "ok" ? "chip good" : "chip warn"} style={{ marginLeft: "auto" }}>{e.status}</span>}
          </div>
          {e.summary && <div className="args" style={{ fontSize: 11, color: "var(--ink-dim)", marginTop: 2 }}>{e.summary}</div>}
        </div>
      </div>
    );
  }
  if (e.kind === "warning") {
    return (
      <div className="ev warn">
        <div className="ts num">{fmtTimeMs(e.ts).slice(0, 12)}</div>
        <div className="body" style={{ borderColor: "var(--warn)" }}>
          <div className="head"><span className="who warn">▲ WARNING</span></div>
          <pre style={{ color: "var(--warn)" }}>{e.text}</pre>
        </div>
      </div>
    );
  }
  if (e.kind === "token_count") {
    const fresh = Math.max(0, e.input - e.cached);
    const pct = (v) => `${(v / (e.total || 1)) * 100}%`;
    const cachePct = e.input ? Math.round((e.cached / e.input) * 100) : 0;
    return (
      <div className="ev token">
        <div className="ts num">{fmtTimeMs(e.ts).slice(0, 12)}</div>
        <div className="body" style={{ borderColor: "var(--rule-soft)" }}>
          <div className="head">
            <span className="who">TOKEN_COUNT</span>
            <span>snapshot</span>
            {delta != null && (
              <span className="chip cyan" style={{ marginLeft: "auto" }}>
                Δ +{(delta / 1000).toFixed(1)}K since last
              </span>
            )}
          </div>
          <div className="tkc">
            <div className="tkc-total">
              <span className="num strong v">{(e.total / 1000).toFixed(1)}K</span>
              <span className="muted">total · {cachePct}% of input cached</span>
            </div>
            <div className="tkc-stack" title={`cached ${e.cached.toLocaleString()} · fresh input ${fresh.toLocaleString()} · output ${e.output.toLocaleString()}`}>
              {e.cached > 0 && <span className="seg cached" style={{ width: pct(e.cached) }}></span>}
              {fresh > 0 && <span className="seg input" style={{ width: pct(fresh) }}></span>}
              {e.output > 0 && <span className="seg output" style={{ width: pct(e.output) }}></span>}
            </div>
            <div className="tkc-legend">
              <span className="cy">cached {(e.cached / 1000).toFixed(1)}K</span>
              <span className="pr">input {(fresh / 1000).toFixed(1)}K</span>
              <span className="am">output {(e.output / 1000).toFixed(1)}K</span>
            </div>
            <div className="tkc-meters">
              <div className="tkc-meter">
                <div className="flex between"><span className="k">Context window</span><span className={"num " + (e.ctx_pct > 60 ? "warn-c" : "strong")}>{e.ctx_pct.toFixed(1)}%</span></div>
                <SegBar count={18} value={e.ctx_pct} hi={e.ctx_pct > 60} />
              </div>
              <div className="tkc-meter">
                <div className="flex between"><span className="k">Rate limit</span><span className={"num " + (e.rate_pct > 60 ? "warn-c" : "strong")}>{e.rate_pct}%</span></div>
                <SegBar count={18} value={e.rate_pct} hi={e.rate_pct > 60} />
              </div>
            </div>
          </div>
        </div>
      </div>
    );
  }
  if (e.kind === "tool_call") {
    const out = outByCall[e.call_id];
    const isSpawn = e.name === "spawn_agent";
    const isWait = e.name === "wait_agent";
    const argSummary = e.args.cmd ? e.args.cmd.join(" ")
      : (e.args.path ? e.args.path
      : (e.args.nickname ? `${e.args.nickname} (${e.args.role}) // ${e.args.task}`
      : (e.args.thread_id ? `await ${e.args.thread_id.slice(0,12)}…` : JSON.stringify(e.args))));
    return (
      <div className={`ev tool${isSpawn ? " spawn" : ""}`}>
        <div className="ts num">{fmtTimeMs(e.ts).slice(0, 12)}</div>
        <div className="body" style={{ borderColor: isSpawn ? "var(--good)" : "var(--amber)" }}>
          <div className="head">
            <span className={`who ${isSpawn ? "spawn" : "tool"}`}>
              {isSpawn ? "⊕ SPAWN_AGENT" : isWait ? "◌ WAIT_AGENT" : `▸ ${e.name.toUpperCase()}`}
            </span>
            <span>call_id {e.call_id}</span>
            {out && <span className={"chip " + (out.fail ? "warn" : "good")}>exit {out.exit} · {Math.round((out.ts - e.ts))}ms</span>}
            {isSpawn && <button onClick={() => onJump(e.spawn_thread_id)} className="chip cyan" style={{ marginLeft: "auto", cursor: "pointer" }}>↗ open child</button>}
          </div>
          <div className="args">$ {argSummary}</div>
          {out && (
            <div className={"out" + (out.fail ? " fail" : "")}>
              <div className="muted" style={{ fontSize: 10, marginBottom: 4, letterSpacing: "0.18em" }}>
                STDOUT · {(out.output || "").length} bytes {out.fail && "· FAILED"}
              </div>
              <pre style={{ fontSize: 11 }}>{out.output}</pre>
            </div>
          )}
        </div>
      </div>
    );
  }
  if (e.kind === "tool_output") return null; // handled inline with tool_call
  return null;
}

function KV({ k, v, tone }) {
  return (
    <div>
      <div className="muted" style={{ fontSize: 9, letterSpacing: "0.2em", textTransform: "uppercase" }}>{k}</div>
      <div className="num strong" style={tone ? { color: `var(--${tone})` } : null}>{v}</div>
    </div>
  );
}

/* ============================================================
   03 — AGENT GRAPH
   ============================================================ */
function GraphView({ selected, setSelected, setView }) {
  // build layout: root + children + grandchildren columns
  const layout = useMemo(() => {
    const root = SESSIONS.find((s) => !s.parent_id && SESSIONS.some((x) => x.parent_id === s.id)) || SESSIONS[0];
    const children = SESSIONS.filter((s) => s.parent_id === root.id);
    const grand = SESSIONS.filter((s) => children.some((c) => c.id === s.parent_id));
    const positions = {};
    // root at left
    positions[root.id] = { x: 60, y: 280 };
    // children spread vertically
    const cSpace = Math.max(120, 540 / Math.max(1, children.length));
    children.forEach((c, i) => {
      positions[c.id] = { x: 380, y: 60 + i * 180 };
    });
    // grandchildren grouped by parent
    grand.forEach((g) => {
      const siblings = grand.filter((x) => x.parent_id === g.parent_id);
      const idx = siblings.indexOf(g);
      const parent = positions[g.parent_id];
      positions[g.id] = { x: 700, y: parent.y - 50 + idx * 90 };
    });
    return { root, children, grand, positions };
  }, []);

  const selectedNode = SESSIONS.find((s) => s.id === selected);
  const isInGraph = layout.root.id === selected || layout.children.some((c) => c.id === selected) || layout.grand.some((g) => g.id === selected);
  const focusNode = isInGraph ? selectedNode : layout.root;

  return (
    <div className="graph">
      <div className="graph-canvas">
        {/* hairline header */}
        <div style={{ position: "absolute", top: 14, left: 14, right: 14, display: "flex", justifyContent: "space-between", color: "var(--ink-dim)", letterSpacing: "0.2em", fontSize: 11, textTransform: "uppercase" }}>
          <span><Reticle /> AGENT TREE · thread_spawn_edges</span>
          <span>DEPTH 2 · {1 + layout.children.length + layout.grand.length} NODES · {EDGES.length} EDGES</span>
        </div>
        {/* axis grid */}
        <div style={{ position: "absolute", inset: 36, pointerEvents: "none" }}>
          {[0, 25, 50, 75, 100].map((p) => (
            <span key={p} style={{ position: "absolute", left: `${p}%`, top: 0, bottom: 0, width: 1, background: "var(--ink-ghost)" }}></span>
          ))}
          <div style={{ position: "absolute", top: 4, left: "50%", color: "var(--ink-dim)", fontSize: 10, letterSpacing: "0.2em" }}>DEPTH·1</div>
          <div style={{ position: "absolute", top: 4, left: "85%", color: "var(--ink-dim)", fontSize: 10, letterSpacing: "0.2em" }}>DEPTH·2</div>
        </div>

        {/* SVG edges */}
        <svg style={{ position: "absolute", inset: 0, pointerEvents: "none", width: "100%", height: "100%" }}>
          <defs>
            <marker id="arr" markerWidth="6" markerHeight="6" refX="6" refY="3" orient="auto">
              <path d="M0,0 L6,3 L0,6 z" fill="var(--primary)" />
            </marker>
            <marker id="arr-warn" markerWidth="6" markerHeight="6" refX="6" refY="3" orient="auto">
              <path d="M0,0 L6,3 L0,6 z" fill="var(--warn)" />
            </marker>
          </defs>
          {EDGES.map((e, i) => {
            const p = layout.positions[e.parent];
            const c = layout.positions[e.child];
            if (!p || !c) return null;
            const x1 = p.x + 220, y1 = p.y + 50;
            const x2 = c.x, y2 = c.y + 50;
            const mx = (x1 + x2) / 2;
            const d = `M ${x1} ${y1} C ${mx} ${y1} ${mx} ${y2} ${x2} ${y2}`;
            const color = e.status === "open" ? "var(--warn)" : "var(--primary)";
            return (
              <g key={i}>
                <path d={d} stroke={color} strokeWidth="1" fill="none" strokeDasharray={e.status === "open" ? "4 4" : "0"} opacity="0.85" markerEnd={e.status === "open" ? "url(#arr-warn)" : "url(#arr)"} />
                <text x={mx} y={(y1 + y2) / 2 - 6} fontSize="9" fill={color} fontFamily="var(--display)" letterSpacing="0.18em" textAnchor="middle" style={{ textTransform: "uppercase" }}>
                  {e.status}
                </text>
              </g>
            );
          })}
        </svg>

        {/* Nodes */}
        {[layout.root, ...layout.children, ...layout.grand].map((s) => {
          const pos = layout.positions[s.id];
          const isRoot = s.id === layout.root.id;
          const status = EDGES.find((e) => e.child === s.id)?.status;
          const open = focusNode.id === s.id;
          const nodeDepth = isRoot ? 0 : (s.parent_id === layout.root.id ? 1 : 2);
          return (
            <div
              key={s.id}
              className={`node ${status === "open" ? "status-open" : ""}`}
              data-open={open}
              data-tone={toneForDepth(nodeDepth)}
              style={{ left: pos.x, top: pos.y }}
              onClick={() => setSelected(s.id)}
              onDoubleClick={() => { setSelected(s.id); setView("timeline"); }}
            >
              <span className="corner-tl"></span>
              <span className="corner-br"></span>
              <div className="role">{isRoot ? "ROOT · USER" : `${s.agent_role?.toUpperCase()} · DEPTH ${s.parent_id === layout.root.id ? "1" : "2"}`}</div>
              <div className="nick">{isRoot ? "ADAM" : s.agent_nickname}</div>
              <div className="id"><ShortId id={s.id} /></div>
              <div className="row" style={{ flexWrap: "wrap" }}>
                <span className="chip dim">{(s.tokens_used/1000).toFixed(1)}K tok</span>
                {s.warnings > 0 && <span className="chip warn">▲{s.warnings}</span>}
                {status && <span className={status === "open" ? "chip warn" : "chip good"}>{status}</span>}
              </div>
            </div>
          );
        })}
      </div>

      {/* INFO PANEL */}
      <aside className="graph-info">
        <div className="panel-tit"><span className="dot"></span><span>Node · Inspector</span><span className="spacer"></span><span className="meta">click = select</span></div>
        <div className="graph-hint">
          <span className="kbd">▸▸</span>
          <span>Double-click a node to open its Timeline</span>
        </div>
        <div style={{ padding: 14, overflow: "auto" }}>
          <HazardTag tone={toneForDepth(sessionDepth(focusNode))} style={{ marginBottom: 12 }}>
            {focusNode.thread_source === "subagent" ? `${depthLabel(sessionDepth(focusNode))} · ${focusNode.agent_nickname}` : "USER · ROOT"}
          </HazardTag>
          <div className="display" style={{ fontSize: 22, color: "var(--ink-strong)", lineHeight: 1.1, marginBottom: 6 }}>{focusNode.title}</div>
          <div className="muted" style={{ fontSize: 11 }}><ShortId id={focusNode.id} /></div>

          <div style={{ marginTop: 14, display: "grid", gridTemplateColumns: "1fr 1fr", gap: 10 }}>
            <Stat label="Tokens" value={(focusNode.tokens_used/1000).toFixed(1) + "K"} />
            <Stat label="Duration" value={`${Math.round(focusNode.duration_ms / 1000)}s`} />
            <Stat label="TTFT" value={`${focusNode.ttft_ms}ms`} />
            <Stat label="Children" value={focusNode.children} tone={focusNode.children_open > 0 ? "warn" : null} sub={focusNode.children_open > 0 ? `${focusNode.children_open} open` : ""} />
          </div>

          <div style={{ marginTop: 16, borderTop: "1px solid var(--rule)", paddingTop: 12 }}>
            <div className="kicker mb-2">▸ Final agent message</div>
            <div className="muted" style={{ fontSize: 12, lineHeight: 1.5 }}>
              {(TIMELINES[focusNode.id] || []).filter((e) => e.kind === "task_complete")[0]?.last_agent_message || "—— in progress ——"}
            </div>
          </div>

          <div style={{ marginTop: 16, borderTop: "1px solid var(--rule)", paddingTop: 12 }}>
            <div className="kicker mb-2">▸ Parent chain</div>
            <ParentChain id={focusNode.id} onJump={(id) => setSelected(id)} />
          </div>

          <button
            onClick={() => setView("timeline")}
            style={{ marginTop: 16, width: "100%", padding: "10px 12px", border: "1px solid var(--primary)", color: "var(--primary)", fontFamily: "var(--display)", letterSpacing: "0.18em", textTransform: "uppercase", fontSize: 11, fontWeight: 700 }}
          >
            ▸ Open Timeline
          </button>

          <div style={{ marginTop: 20 }}>
            <div className="kicker mb-2">▸ Legend</div>
            <div className="flex gap-2" style={{ flexDirection: "column", fontSize: 11 }}>
              <div className="flex gap-2"><span style={{ width: 16, height: 1, background: "var(--primary)", marginTop: 6 }}></span><span>closed edge · child reported back</span></div>
              <div className="flex gap-2"><span style={{ width: 16, height: 1, background: "var(--warn)", marginTop: 6, borderTop: "1px dashed var(--warn)" }}></span><span>open edge · still awaiting</span></div>
            </div>
          </div>
        </div>
      </aside>
    </div>
  );
}

function ParentChain({ id, onJump }) {
  const chain = [];
  let cursor = SESSIONS.find((s) => s.id === id);
  while (cursor) {
    chain.unshift(cursor);
    cursor = cursor.parent_id ? SESSIONS.find((s) => s.id === cursor.parent_id) : null;
  }
  return (
    <div>
      {chain.map((s, i) => (
        <div key={s.id} onClick={() => onJump(s.id)} style={{ display: "flex", alignItems: "baseline", gap: 8, padding: "4px 0", cursor: "pointer", fontSize: 11 }}>
          <span className="muted">{"› ".repeat(i)}</span>
          <span className="strong">{s.thread_source === "subagent" ? s.agent_nickname : "ADAM"}</span>
          <span className="muted"><ShortId id={s.id} /></span>
        </div>
      ))}
    </div>
  );
}

/* ============================================================
   04 — TOKENS
   ============================================================ */

// Per-session token composition. Uses the last token_count snapshot when the
// session has one; otherwise synthesizes a deterministic split from tokens_used
// (seeded by id so it doesn't flicker between renders).
function tokenBreakdown(s) {
  const snaps = (TIMELINES[s.id] || []).filter((e) => e.kind === "token_count");
  const last = snaps[snaps.length - 1];
  let total, input, output, cached;
  if (last) {
    ({ total, input, output, cached } = last);
  } else {
    total = s.tokens_used;
    const h = [...s.id].reduce((a, c) => a + c.charCodeAt(0), 0);
    output = Math.round(total * (0.12 + (h % 7) / 100));      // ~12–18% output
    input = total - output;
    cached = Math.round(input * (0.30 + (h % 40) / 100));     // 30–70% of input cached
  }
  const freshInput = Math.max(0, input - cached);
  return { total, input, output, cached, freshInput };
}

function TokenBudget({ sessions, onSelect }) {
  const ranked = [...sessions].sort((a, b) => b.tokens_used - a.tokens_used).slice(0, 6);
  return (
    <div className="tok-budget">
      {ranked.map((s, i) => {
        const b = tokenBreakdown(s);
        const pct = (v) => `${(v / b.total) * 100}%`;
        const cachePct = b.input ? Math.round((b.cached / b.input) * 100) : 0;
        const outPct = b.total ? Math.round((b.output / b.total) * 100) : 0;
        const isSub = s.thread_source === "subagent";
        return (
          <button key={s.id} className="tok-row" onClick={() => onSelect(s.id)}>
            <span className="rank num">{pad(i + 1, 2)}</span>
            <span className="tok-row-body">
              <span className="tok-row-head">
                <span className="ttl">
                  {isSub && <span className="sub-tag" data-tone={toneForDepth(sessionDepth(s))}>{sessionDepth(s) >= 2 ? "SUB²" : "SUB"}</span>}
                  {isSub ? s.agent_nickname : s.title}
                </span>
                <span className="cache num" title="cache hit ratio of input">◇ {cachePct}%</span>
                <span className="tot num">{(b.total / 1000).toFixed(1)}K</span>
              </span>
              <span className="tok-stack" title={`cached ${b.cached.toLocaleString()} · fresh input ${b.freshInput.toLocaleString()} · output ${b.output.toLocaleString()}`}>
                {b.cached > 0 && <span className="seg cached" style={{ width: pct(b.cached) }}></span>}
                {b.freshInput > 0 && <span className="seg input" style={{ width: pct(b.freshInput) }}></span>}
                {b.output > 0 && <span className="seg output" style={{ width: pct(b.output) }}></span>}
              </span>
            </span>
          </button>
        );
      })}
    </div>
  );
}

// Per-session token composition: a stacked bar tied to a labeled breakdown
// (cached input / fresh input / output) with absolute values, % of total, and
// billing notes — plus the context-window gauge. Replaces the loose readouts.
function SessionTokenComposition({ snap, snapshots }) {
  const total = snap.total || 1;
  const freshInput = Math.max(0, snap.input - snap.cached);
  const reasoning = Math.round(snap.output * 0.3);
  const pct = (v) => (v / total) * 100;
  const rows = [
    { key: "cached", label: "Cached input", v: snap.cached, color: "var(--cyan)", note: "billed at reduced rate" },
    { key: "input", label: "Fresh input", v: freshInput, color: "var(--primary)", note: "full-rate prompt" },
    { key: "output", label: "Output", v: snap.output, color: "var(--amber)", note: `~${reasoning.toLocaleString()} reasoning` },
  ];
  return (
    <div className="stc">
      <div className="stc-top">
        <div>
          <div className="display num stc-total">{(snap.total / 1000).toFixed(1)}K</div>
          <div className="kicker">Σ tokens · {snapshots} snapshot{snapshots === 1 ? "" : "s"}</div>
        </div>
        <div className="stc-ctx">
          <div className="flex between mb-1" style={{ fontSize: 10, letterSpacing: "0.18em", textTransform: "uppercase", color: "var(--ink-dim)" }}>
            <span>Context window</span>
            <span className={"num strong " + (snap.ctx_pct > 60 ? "warn-c" : "")}>{snap.ctx_pct.toFixed(1)}%</span>
          </div>
          <SegBar count={20} value={snap.ctx_pct} hi={snap.ctx_pct > 60} />
          <div className="muted" style={{ fontSize: 9, marginTop: 4, letterSpacing: "0.14em", textTransform: "uppercase" }}>of 200K window</div>
        </div>
      </div>

      <div className="stc-stack" title="cached / fresh input / output">
        {rows.map((r) => r.v > 0 && (
          <div key={r.key} className="seg" style={{ width: `${pct(r.v)}%`, background: r.color }}></div>
        ))}
      </div>

      <div className="stc-rows">
        {rows.map((r) => (
          <div key={r.key} className="stc-row">
            <span className="sw" style={{ background: r.color }}></span>
            <span className="lb">{r.label}</span>
            <span className="nt">{r.note}</span>
            <span className="vl num">{r.v.toLocaleString()}</span>
            <span className="pc num">{pct(r.v).toFixed(0)}%</span>
          </div>
        ))}
      </div>
    </div>
  );
}

function TokensView({ session, setSelected, setView }) {
  const tokens = TIMELINES[session.id]?.filter((e) => e.kind === "token_count") || [];
  const lastSnap = tokens[tokens.length - 1] || { total: session.tokens_used, input: 0, output: 0, cached: 0, ctx_pct: (session.tokens_used / 200000) * 100, rate_pct: 30 };

  // build aggregate series across all sessions for the top chart
  const allBuckets = useMemo(() => {
    const n = 36;
    const arr = new Array(n).fill(0);
    SESSIONS.forEach((s) => {
      const span = NOW - s.created_at;
      const idx = Math.min(n - 1, Math.max(0, Math.floor((n - 1) * (1 - (NOW - s.updated_at) / (span + 1)))));
      arr[idx] += s.tokens_used;
    });
    return arr;
  }, []);

  // build a smooth cumulative curve from tokens snapshots for this session
  const curvePoints = useMemo(() => {
    if (!tokens.length) return [];
    const t0 = tokens[0].ts;
    const tN = tokens[tokens.length - 1].ts;
    const span = Math.max(1, tN - t0);
    return tokens.map((p) => ({ x: ((p.ts - t0) / span) * 100, y: 100 - Math.min(100, (p.total / 100000) * 100), v: p }));
  }, [tokens]);

  return (
    <div className="tokens">
      <section>
        <div className="panel-tit" style={{ border: 0, padding: 0, height: "auto", marginBottom: 12 }}>
          <span className="dot"></span><span>Aggregate token flow · all sessions · 36-bucket</span>
          <span className="spacer"></span>
          <span className="meta num">Σ {(SESSIONS.reduce((a, s) => a + s.tokens_used, 0)/1000).toFixed(0)}K</span>
        </div>
        <BigBars data={allBuckets} />
      </section>

      <div className="row2">
        <section>
          <div className="panel-tit" style={{ border: 0, padding: 0, height: "auto", marginBottom: 10 }}>
            <span className="dot"></span><span>Session · {session.title.slice(0, 38)}</span>
          </div>
          <SessionTokenComposition snap={lastSnap} snapshots={tokens.length} />
        </section>

        <section style={{ gridColumn: "span 2" }}>
          <div className="panel-tit" style={{ border: 0, padding: 0, height: "auto", marginBottom: 10 }}>
            <span className="dot"></span><span>Token curve · token_count snapshots</span>
            <span className="spacer"></span>
            <span className="meta">SCALE 0–100K</span>
          </div>
          <TokenCurve points={curvePoints} />
        </section>
      </div>

      <div className="row2">
        <section>
          <div className="panel-tit" style={{ border: 0, padding: 0, height: "auto", marginBottom: 10 }}>
            <span className="dot"></span><span>Rate limits</span>
          </div>
          <RateLimitMeter label="Primary" pct={54} resetIn="2h 12m" />
          <RateLimitMeter label="Secondary" pct={18} resetIn="6h 02m" />
          <RateLimitMeter label="Output cap · 5h" pct={72} resetIn="0h 48m" tone="warn" />
          <div className="muted" style={{ fontSize: 10, marginTop: 8, letterSpacing: "0.18em", textTransform: "uppercase" }}>plan · max-200 · reset at 19:48 UTC</div>
        </section>

        <section>
          <div className="panel-tit" style={{ border: 0, padding: 0, height: "auto", marginBottom: 10 }}>
            <span className="dot"></span><span>Token budget · by session</span>
            <span className="spacer"></span>
            <span className="tok-legend">
              <span className="cy">cached</span>
              <span className="pr">input</span>
              <span className="am">output</span>
            </span>
          </div>
          <TokenBudget sessions={SESSIONS} onSelect={(id) => { setSelected(id); setView("timeline"); }} />
        </section>

        <section>
          <div className="panel-tit" style={{ border: 0, padding: 0, height: "auto", marginBottom: 10 }}>
            <span className="dot"></span><span>Cached input ratio · last 12 snapshots</span>
          </div>
          <CachedRatio session={session} />
          <div className="muted" style={{ fontSize: 10, marginTop: 10, letterSpacing: "0.18em", textTransform: "uppercase" }}>
            higher · better. cache hits reduce billed input.
          </div>
        </section>
      </div>
    </div>
  );
}

function BigBars({ data }) {
  const max = Math.max(...data, 1);
  return (
    <div style={{ display: "flex", alignItems: "flex-end", gap: 4, height: "100%", minHeight: 0 }}>
      {data.map((v, i) => (
        <div key={i} style={{ flex: 1, display: "flex", flexDirection: "column", alignItems: "center", gap: 4, height: "100%", minHeight: 0 }}>
          <div style={{ flex: 1, width: "100%", display: "flex", alignItems: "flex-end" }}>
            <div style={{
              width: "100%",
              height: `${(v / max) * 100}%`,
              background: v / max > 0.8 ? "var(--warn)" : "var(--primary)",
              boxShadow: `0 0 8px ${v / max > 0.8 ? "var(--warn)" : "var(--primary)"}`,
              backgroundImage: "linear-gradient(to bottom, rgba(255,255,255,0.15), rgba(255,255,255,0))",
            }}></div>
          </div>
          <div className="num" style={{ fontSize: 8, color: "var(--ink-dim)" }}>{i % 6 === 0 ? `${-36+i}m` : ""}</div>
        </div>
      ))}
    </div>
  );
}

function MiniReadout({ label, value, tone }) {
  return (
    <Bracket style={{ padding: "8px 10px", border: "1px solid var(--rule)" }}>
      <div className="kicker" style={{ fontSize: 10 }}>{label}</div>
      <div className="display num" style={{ fontSize: 18, color: tone ? `var(--${tone})` : "var(--ink-strong)" }}>{value}</div>
    </Bracket>
  );
}

function RateLimitMeter({ label, pct, resetIn, tone }) {
  return (
    <div style={{ marginBottom: 12 }}>
      <div className="flex between mb-1" style={{ fontSize: 11 }}>
        <span className="kicker" style={{ color: tone === "warn" ? "var(--warn)" : "var(--ink-dim)" }}>{label}</span>
        <span className="num strong" style={{ color: tone === "warn" ? "var(--warn)" : "var(--ink-strong)" }}>{pct}%</span>
      </div>
      <SegBar count={28} value={pct} hi={tone === "warn"} />
      <div className="muted" style={{ fontSize: 10, marginTop: 4, letterSpacing: "0.18em", textTransform: "uppercase" }}>resets in {resetIn}</div>
    </div>
  );
}

function CachedRatio({ session }) {
  // synthesize 12 snapshots
  const vals = useMemo(() => {
    const arr = [];
    let base = 0.05;
    for (let i = 0; i < 12; i++) {
      base = Math.min(0.78, base + Math.random() * 0.12);
      arr.push(base);
    }
    return arr;
  }, [session.id]);
  return (
    <div style={{ display: "flex", alignItems: "flex-end", gap: 4, height: 120 }}>
      {vals.map((v, i) => (
        <div key={i} style={{ flex: 1, display: "flex", flexDirection: "column", alignItems: "center", gap: 4 }}>
          <div className="num" style={{ fontSize: 9, color: "var(--ink-dim)" }}>{Math.round(v * 100)}%</div>
          <div style={{ width: "100%", height: `${v * 100}%`, background: "var(--cyan)", boxShadow: "0 0 6px var(--cyan)" }}></div>
        </div>
      ))}
    </div>
  );
}

function TokenCurve({ points }) {
  if (!points.length) return <div className="muted">no snapshots</div>;
  const W = 1000, H = 200;
  const pathD = points.map((p, i) => `${i === 0 ? "M" : "L"} ${(p.x / 100) * W} ${(p.y / 100) * H}`).join(" ");
  const fillD = pathD + ` L ${W} ${H} L 0 ${H} Z`;
  return (
    <svg viewBox={`0 0 ${W} ${H}`} preserveAspectRatio="none" style={{ width: "100%", height: "100%", display: "block" }}>
      <defs>
        <linearGradient id="tg" x1="0" y1="0" x2="0" y2="1">
          <stop offset="0%" stopColor="var(--primary)" stopOpacity="0.45" />
          <stop offset="100%" stopColor="var(--primary)" stopOpacity="0" />
        </linearGradient>
      </defs>
      {/* grid */}
      {[0, 25, 50, 75, 100].map((p) => (
        <g key={p}>
          <line x1={0} x2={W} y1={(p / 100) * H} y2={(p / 100) * H} stroke="var(--ink-ghost)" strokeWidth="1" />
          <text x={6} y={(p / 100) * H - 4} fontSize="10" fill="var(--ink-dim)" fontFamily="var(--mono)">{100 - p}K</text>
        </g>
      ))}
      <path d={fillD} fill="url(#tg)" />
      <path d={pathD} stroke="var(--primary)" strokeWidth="1.5" fill="none" style={{ filter: "drop-shadow(0 0 4px var(--primary))" }} />
      {points.map((p, i) => (
        <g key={i}>
          <circle cx={(p.x / 100) * W} cy={(p.y / 100) * H} r="4" fill="var(--bg-0)" stroke="var(--primary)" strokeWidth="1.5" />
          <text x={(p.x / 100) * W + 8} y={(p.y / 100) * H - 8} fontSize="10" fill="var(--ink-strong)" fontFamily="var(--mono)">{(p.v.total/1000).toFixed(1)}K</text>
        </g>
      ))}
    </svg>
  );
}

/* ============================================================
   05 — DIAGNOSTICS
   ============================================================ */
function DiagnosticsView({ session, setSelected, setView }) {
  const [level, setLevel] = useState("WARN");
  const [target, setTarget] = useState("all");
  const [scope, setScope] = useState("this");
  const [tail, setTail] = useState(true);

  // simulate live tail with a "now" ticker
  useEffect(() => {
    if (!tail) return;
    const id = setInterval(() => {}, 1500);
    return () => clearInterval(id);
  }, [tail]);

  const filtered = LOGS.filter((l) => {
    if (level !== "all" && l.level !== level) return false;
    if (target !== "all" && l.target !== target) return false;
    if (scope === "this" && l.thread_id !== session.id) return false;
    return true;
  }).slice(0, 200);

  // target stats
  const targetCounts = useMemo(() => {
    const c = {};
    LOGS.forEach((l) => { c[l.target] = (c[l.target] || 0) + 1; });
    return Object.entries(c).sort((a, b) => b[1] - a[1]);
  }, []);

  // warning counts by thread
  const warnByThread = useMemo(() => {
    const c = {};
    LOGS.filter((l) => l.level === "WARN").forEach((l) => { c[l.thread_id] = (c[l.thread_id] || 0) + 1; });
    return Object.entries(c).sort((a, b) => b[1] - a[1]);
  }, []);

  return (
    <div className="diag">
      <aside>
        <div style={{ padding: "12px 14px", borderBottom: "1px solid var(--rule)" }}>
          <div className="kicker" style={{ color: "var(--primary)" }}>▸ Filter</div>
          <div className="display" style={{ fontSize: 18, color: "var(--ink-strong)", marginTop: 4 }}>LOG STREAM</div>
          <div className="muted" style={{ fontSize: 11 }}>logs_2.sqlite · 406,883 rows</div>
        </div>

        <div className="filter-grp">
          <div className="lbl">Level</div>
          <div className="row">
            {["all", "WARN", "INFO", "DEBUG", "TRACE"].map((v) => (
              <button key={v} className="opt" data-on={level === v} onClick={() => setLevel(v)}>{v}</button>
            ))}
          </div>
        </div>
        <div className="filter-grp">
          <div className="lbl">Scope</div>
          <div className="row">
            <button className="opt" data-on={scope === "this"} onClick={() => setScope("this")}>This session</button>
            <button className="opt" data-on={scope === "all"} onClick={() => setScope("all")}>All threads</button>
          </div>
        </div>

        <div className="filter-grp" style={{ flex: 1, overflow: "auto" }}>
          <div className="lbl">Target · top 10</div>
          <button className="opt" data-on={target === "all"} onClick={() => setTarget("all")} style={{ marginBottom: 6, width: "100%", textAlign: "left" }}>all targets</button>
          {targetCounts.slice(0, 10).map(([t, n]) => (
            <button key={t} className="opt" data-on={target === t} onClick={() => setTarget(t)} style={{ display: "flex", justifyContent: "space-between", width: "100%", marginBottom: 4, textAlign: "left" }}>
              <span style={{ overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap", maxWidth: 180 }}>{t}</span>
              <span className="num">{n}</span>
            </button>
          ))}
        </div>

        <div className="filter-grp" style={{ borderTop: "1px solid var(--rule)" }}>
          <div className="lbl">Mode</div>
          <button className="opt" data-on={tail} onClick={() => setTail(!tail)} style={{ display: "flex", gap: 6 }}>
            <span className={tail ? "warn-c blink" : "faint"}>●</span> {tail ? "Tail · live" : "Paused"}
          </button>
        </div>
      </aside>

      <main>
        <div style={{ padding: "10px 14px", borderBottom: "1px solid var(--rule)", display: "flex", alignItems: "center", gap: 12, background: "var(--bg-1)" }}>
          <span className="kicker">{scope === "this" ? "▸ This session" : "▸ All threads"} · {level} · {target}</span>
          <span className="spacer" style={{ flex: 1 }}></span>
          <span className="muted num">{filtered.length} rows</span>
          <span className="warn-c blink">{tail ? "● LIVE" : ""}</span>
        </div>
        <div style={{ overflow: "auto" }}>
          {filtered.length === 0 && <div className="muted" style={{ padding: 30, textAlign: "center", letterSpacing: "0.2em" }}>—— no rows match filter ——</div>}
          {filtered.map((l, i) => (
            <div key={l.id + "-" + i} className={`log-row ${l.level}`}>
              <span className="ts num">{fmtTimeMs(l.ts).slice(0, 12)}</span>
              <span><span className={"lvl " + l.level}></span>{l.level}</span>
              <span className="tgt">{l.target}</span>
              <span className="msg">{l.msg} {l.thread_id !== session.id && <span className="muted" style={{ fontSize: 10 }}>· {l.thread_id.slice(0, 8)}…</span>}</span>
            </div>
          ))}
        </div>
      </main>

      <aside className="right">
        <div style={{ padding: "12px 14px", borderBottom: "1px solid var(--rule)" }}>
          <div className="kicker" style={{ color: "var(--primary)" }}>▸ Health</div>
          <div className="display" style={{ fontSize: 18, color: "var(--ink-strong)", marginTop: 4 }}>RUNTIME</div>
        </div>

        <div style={{ padding: 14, borderBottom: "1px solid var(--rule)" }}>
          <div className="kicker mb-2">▸ Warn count · 5 min</div>
          <VBars data={[1, 0, 2, 4, 0, 1, 8, 3, 1, 2, 0, 0]} color="var(--warn)" h={48} />
          <div className="flex between" style={{ fontSize: 10, color: "var(--ink-dim)", letterSpacing: "0.18em", marginTop: 4 }}>
            <span>5m AGO</span><span>NOW</span>
          </div>
        </div>

        <div style={{ padding: 14, borderBottom: "1px solid var(--rule)" }}>
          <div className="kicker mb-2">▸ Loudest threads</div>
          {warnByThread.slice(0, 5).map(([id, n]) => {
            const s = SESSIONS.find((x) => x.id === id);
            return (
              <div key={id} onClick={() => s && setSelected(s.id)} style={{ display: "flex", justifyContent: "space-between", padding: "5px 0", borderBottom: "1px dashed var(--rule-soft)", cursor: "pointer", fontSize: 11 }}>
                <span className="strong">{s ? (s.agent_nickname || "USER") : id.slice(0, 8)}</span>
                <span className="warn-c num">▲ {n}</span>
              </div>
            );
          })}
        </div>

        <div style={{ padding: 14, borderBottom: "1px solid var(--rule)" }}>
          <div className="kicker mb-2">▸ Plugin loader</div>
          <div style={{ fontSize: 11, lineHeight: 1.6 }}>
            <div className="warn-c">▲ skill 'read_pdf' manifest missing 'description'</div>
            <div className="warn-c">▲ duplicate id 'pdf-extract' shadowed</div>
            <div className="good-c">✓ 18 skills loaded · 42ms</div>
          </div>
        </div>

        <div style={{ padding: 14, flex: 1, overflow: "auto" }}>
          <div className="kicker mb-2">▸ Raw fallback</div>
          <div className="muted" style={{ fontSize: 11, lineHeight: 1.5 }}>
            <code>~/.codex/log/codex-tui.log</code> · 24.6 MB
            <div style={{ marginTop: 6 }}>not parsed — open via raw tail view (advanced).</div>
          </div>
          <button style={{ marginTop: 12, padding: "8px 12px", border: "1px solid var(--rule)", color: "var(--ink-dim)", fontFamily: "var(--display)", letterSpacing: "0.18em", textTransform: "uppercase", fontSize: 10, fontWeight: 700 }}>
            ▸ Open raw tail
          </button>
        </div>
      </aside>
    </div>
  );
}

/* mount */
const root = ReactDOM.createRoot(document.getElementById("root"));
root.render(<App />);
